(function () {

  // ---------- ambient effects (run on any page) ----------

  // rising bubbles in the hero
  const bubbleWrap = document.getElementById('bubbles');
  if (bubbleWrap && !window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
    const COUNT = 14;
    for (let i = 0; i < COUNT; i++) {
      const b = document.createElement('span');
      const size = 6 + Math.random() * 22;
      b.style.width = size + 'px';
      b.style.height = size + 'px';
      b.style.left = Math.random() * 100 + '%';
      b.style.animationDuration = (9 + Math.random() * 14) + 's';
      b.style.animationDelay = (Math.random() * -20) + 's';
      bubbleWrap.appendChild(b);
    }
  }

  // scroll reveal
  const revealEls = document.querySelectorAll('[data-reveal]');
  if (revealEls.length && 'IntersectionObserver' in window) {
    const io = new IntersectionObserver((entries) => {
      entries.forEach(en => {
        if (en.isIntersecting) { en.target.classList.add('in'); io.unobserve(en.target); }
      });
    }, { threshold: 0.15 });
    revealEls.forEach(el => io.observe(el));
  } else {
    revealEls.forEach(el => el.classList.add('in'));
  }

   const form = document.getElementById('dietForm');
     if (!form) return; // script also loads harmlessly on 

     const heightInput = document.getElementById('height');
       const weightInput = document.getElementById('weight');
         const ageInput = document.getElementById('age');
           const sexInput = document.getElementById('sex');
             const activityInput = document.getElementById('activity');
               const heightUnitLabel = document.getElementById('heightUnit');
                 const weightUnitLabel = document.getElementById('weightUnit');
                   const formError = document.getElementById('formError');

                     const metricBtn = document.getElementById('unitMetricBtn');
                       const imperialBtn = document.getElementById('unitImperialBtn');
                         let units = 'metric';

                           function setUnits(next) {
                                if (next === units) return;
                                    const h = parseFloat(heightInput.value);
                                        const w = parseFloat(weightInput.value);

                                            if (next === 'imperial') {
                                                      if (!isNaN(h)) heightInput.value = round1(h / 2.54);    // cm -> in
                                                            if (!isNaN(w)) weightInput.value = round1(w * 2.20462); // kg -> lb
                                                                  heightUnitLabel.textContent = '(in)';
                                                                        weightUnitLabel.textContent = '(lb)';
                                                                              heightInput.placeholder = 'e.g. 69';
                                                                                    weightInput.placeholder = 'e.g. 172';
                                            } else {
                                                      if (!isNaN(h)) heightInput.value = round1(h * 2.54);
                                                            if (!isNaN(w)) weightInput.value = round1(w / 2.20462);
                                                                  heightUnitLabel.textContent = '(cm)';
                                                                        weightUnitLabel.textContent = '(kg)';
                                                                              heightInput.placeholder = 'e.g. 175';
                                                                                    weightInput.placeholder = 'e.g. 78';
                                            }

                                                units = next;
                                                    metricBtn.classList.toggle('active', units === 'metric');
                                                        imperialBtn.classList.toggle('active', units === 'imperial');
                                        }
                                          metricBtn.addEventListener('click', () => setUnits('metric'));
                                            imperialBtn.addEventListener('click', () => setUnits('imperial'));

                                              function round1(n) { return Math.round(n * 10) / 10; }

                                                const goalPills = document.querySelectorAll('.goal-pill');
                                                  goalPills.forEach(pill => {
                                                        const radio = pill.querySelector('input');
                                                            radio.addEventListener('change', () => {
                                                                      goalPills.forEach(p => p.classList.remove('checked'));
                                                                            pill.classList.add('checked');
                                                            });
                                                        });

                                                          const GOAL_DEFICITS = { mild: 275, moderate: 550, aggressive: 825 };
                                                            const GOAL_LABELS = { mild: ' 0.25 kg / week', moderate: ' 0.5 kg / week', aggressive: ' 0.75 kg / week' };

                                                              function matchProgram(bmiCategory, goal) {
                                                                    if (goal === 'aggressive') {
                                                                              return {
                                                                                        name: 'Structured Lower-Carb',
                                                                                                tag: 'HIGHER PROTEIN  LOWER CARB',
                                                                                                        desc: 'Carbohydrates are deliberately reduced and swapped for protein and fibrous veg, which tends to blunt hunger during a faster deficit. Best kept to a few months at a time.',
                                                                                                                meals: [
                                                                                                                              ['Breakfast', 'Eggs or Greek yogurt with berries, no refined grains'],
                                                                                                                                        ['Lunch', 'Large salad, lean protein (chicken, fish, tofu), olive oil dressing'],
                                                                                                                                                  ['Dinner', 'Grilled protein, roasted non-starchy vegetables'],
                                                                                                                                                            ['Snack', 'Nuts, cottage cheese, or a protein shake'],
                                                                                                                ]
                                                                                                            };
                                                                                                        }
                                                                                                            if (bmiCategory === 'obese') {
                                                                                                                      return {
                                                                                                                                name: 'High-Protein Reset',
                                                                                                                                        tag: 'PROTEIN-FORWARD',
                                                                                                                                                desc: 'Every meal is built around a protein source first, which research links to better fullness and less muscle loss during a deficit  carbs and fat fill the remaining budget.',
                                                                                                                                                        meals: [
                                                                                                                                                                      ['Breakfast', 'Protein-forward option: eggs, skyr, or a protein oatmeal'],
                                                                                                                                                                                ['Lunch', 'Lean protein + whole grain + generous vegetables'],
                                                                                                                                                                                          ['Dinner', 'Fish or poultry, legumes, roasted vegetables'],
                                                                                                                                                                                                    ['Snack', 'Protein yogurt or a handful of nuts'],
                                                                                                                                                        ]
                                                                                                                                                    };
                                                                                                                                                }
                                                                                                                                                    if (goal === 'mild') {
                                                                                                                                                              return {
                                                                                                                                                                        name: 'Plate-Method Steady State',
                                                                                                                                                                                tag: 'LOW-FRICTION',
                                                                                                                                                                                        desc: 'No tracking required: half the plate is vegetables, a quarter lean protein, a quarter whole-grain carbs. Built for people who want a mild, very sustainable deficit.',
                                                                                                                                                                                                meals: [
                                                                                                                                                                                                              ['Breakfast', 'Whole-grain toast, eggs, fruit'],
                                                                                                                                                                                                                        ['Lunch', 'Half-plate veg, quarter protein, quarter whole grain'],
                                                                                                                                                                                                                                  ['Dinner', 'Same plate method, lighter portion'],
                                                                                                                                                                                                                                            ['Snack', 'Fruit or a small handful of nuts'],
                                                                                                                                                                                                ]
                                                                                                                                                                                            };
                                                                                                                                                                                        }
                                                                                                                                                                                            return {
                                                                                                                                                                                                      name: 'Mediterranean Balance',
                                                                                                                                                                                                            tag: 'FLEXIBLE & SUSTAINABLE',
                                                                                                                                                                                                                  desc: 'Vegetables, legumes, whole grains, fish and olive oil form the base, with red meat and processed food kept occasional. Consistently one of the easiest patterns to stick to long-term.',
                                                                                                                                                                                                                        meals: [
                                                                                                                                                                                                                                    ['Breakfast', 'Greek yogurt, nuts, seasonal fruit'],
                                                                                                                                                                                                                                            ['Lunch', 'Legume or fish salad, olive oil, whole grains'],
                                                                                                                                                                                                                                                    ['Dinner', 'Grilled fish or chicken, vegetables, small grain portion'],
                                                                                                                                                                                                                                                            ['Snack', 'Fruit, olives, or a small handful of almonds'],
                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                    };
                                                                                                                                                                                                                }

                                                                                                                                                                                                                  function bmiCategoryOf(bmi) {
                                                                                                                                                                                                                        if (bmi < 18.5) return { key: 'underweight', label: 'Underweight', color: '#6ab2ef' };
                                                                                                                                                                                                                            if (bmi < 25) return { key: 'normal', label: 'Healthy range', color: '#2dd4bf' };
                                                                                                                                                                                                                                if (bmi < 30) return { key: 'overweight', label: 'Overweight', color: '#e0b34c' };
                                                                                                                                                                                                                                    return { key: 'obese', label: 'Obese', color: '#ff8a65' };
                                                                                                                                                                                                                  }

                                                                                                                                                                                                                    const resultsEmpty = document.getElementById('resultsEmpty');
                                                                                                                                                                                                                      const resultsContent = document.getElementById('resultsContent');
                                                                                                                                                                                                                        const gaugeBmi = document.getElementById('gaugeBmi');
                                                                                                                                                                                                                          const gaugeLiquid = document.getElementById('gaugeLiquid');
                                                                                                                                                                                                                            const bmiCategoryEl = document.getElementById('bmiCategory');
                                                                                                                                                                                                                              const bmiMarker = document.getElementById('bmiMarker');
                                                                                                                                                                                                                                const statBmr = document.getElementById('statBmr');
                                                                                                                                                                                                                                  const statTdee = document.getElementById('statTdee');
                                                                                                                                                                                                                                    const statTarget = document.getElementById('statTarget');
                                                                                                                                                                                                                                      const statPace = document.getElementById('statPace');
                                                                                                                                                                                                                                        const barProtein = document.getElementById('barProtein');
                                                                                                                                                                                                                                          const barCarb = document.getElementById('barCarb');
                                                                                                                                                                                                                                            const barFat = document.getElementById('barFat');
                                                                                                                                                                                                                                              const legProtein = document.getElementById('legProtein');
                                                                                                                                                                                                                                                const legCarb = document.getElementById('legCarb');
                                                                                                                                                                                                                                                  const legFat = document.getElementById('legFat');
                                                                                                                                                                                                                                                    const planName = document.getElementById('planName');
                                                                                                                                                                                                                                                      const planTag = document.getElementById('planTag');
                                                                                                                                                                                                                                                        const planDesc = document.getElementById('planDesc');
                                                                                                                                                                                                                                                          const planMeals = document.getElementById('planMeals');
                                                                                                                                                                                                                                                            const lowCalWarning = document.getElementById('lowCalWarning');

                                                                                                                                                                                                                                                              function animateCount(el, target, suffix, duration) {
                                                                                                                                                                                                                                                                    const start = 0;
                                                                                                                                                                                                                                                                        const startTime = performance.now();
                                                                                                                                                                                                                                                                            function tick(now) {
                                                                                                                                                                                                                                                                                      const p = Math.min(1, (now - startTime) / duration);
                                                                                                                                                                                                                                                                                            const eased = 1 - Math.pow(1 - p, 3);
                                                                                                                                                                                                                                                                                                  el.textContent = Math.round(start + (target - start) * eased).toLocaleString() + suffix;
                                                                                                                                                                                                                                                                                                        if (p < 1) requestAnimationFrame(tick);
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                requestAnimationFrame(tick);
                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                          form.addEventListener('submit', function (e) {
                                                                                                                                                                                                                                                                                e.preventDefault();

                                                                                                                                                                                                                                                                                    let heightCm = parseFloat(heightInput.value);
                                                                                                                                                                                                                                                                                        let weightKg = parseFloat(weightInput.value);
                                                                                                                                                                                                                                                                                            const age = parseFloat(ageInput.value);
                                                                                                                                                                                                                                                                                                const sex = sexInput.value;
                                                                                                                                                                                                                                                                                                    const activity = parseFloat(activityInput.value);
                                                                                                                                                                                                                                                                                                        const goal = form.querySelector('input[name="goal"]:checked').value;

                                                                                                                                                                                                                                                                                                            if (units === 'imperial') {
                                                                                                                                                                                                                                                                                                                      heightCm = heightCm * 2.54;
                                                                                                                                                                                                                                                                                                                            weightKg = weightKg / 2.20462;
                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                const valid = heightCm > 90 && heightCm < 260 && weightKg > 25 && weightKg < 400 && age >= 14 && age <= 90;
                                                                                                                                                                                                                                                                                                                    if (!valid || isNaN(heightCm) || isNaN(weightKg) || isNaN(age)) {
                                                                                                                                                                                                                                                                                                                              formError.classList.add('show');
                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                        formError.classList.remove('show');

                                                                                                                                                                                                                                                                                                                            // BMI
                                                                                                                                                                                                                                                                                                                                const heightM = heightCm / 100;
                                                                                                                                                                                                                                                                                                                                    const bmi = weightKg / (heightM * heightM);
                                                                                                                                                                                                                                                                                                                                        const cat = bmiCategoryOf(bmi);

                                                                                                                                                                                                                                                                                                                                            // Mifflin-St Jeor
                                                                                                                                                                                                                                                                                                                                                let bmr = 10 * weightKg + 6.25 * heightCm - 5 * age;
                                                                                                                                                                                                                                                                                                                                                    bmr += sex === 'male' ? 5 : -161;

                                                                                                                                                                                                                                                                                                                                                        const tdee = bmr * activity;

                                                                                                                                                                                                                                                                                                                                                            // calorie target with safety floor
                                                                                                                                                                                                                                                                                                                                                                const deficit = GOAL_DEFICITS[goal];
                                                                                                                                                                                                                                                                                                                                                                    let target = tdee - deficit;
                                                                                                                                                                                                                                                                                                                                                                        const safeFloor = sex === 'male' ? 1500 : 1200;
                                                                                                                                                                                                                                                                                                                                                                            let capped = false;
                                                                                                                                                                                                                                                                                                                                                                                if (target < safeFloor) { target = safeFloor; capped = true; }
                                                                                                                                                                                                                                                                                                                                                                                    if (target < bmr * 0.85) { target = Math.round(bmr * 0.85); capped = true; }

                                                                                                                                                                                                                                                                                                                                                                                        // macros
                                                                                                                                                                                                                                                                                                                                                                                            let proteinG = weightKg * 2;
                                                                                                                                                                                                                                                                                                                                                                                                let proteinKcal = proteinG * 4;
                                                                                                                                                                                                                                                                                                                                                                                                    let fatKcal = target * 0.25;
                                                                                                                                                                                                                                                                                                                                                                                                        let fatG = fatKcal / 9;
                                                                                                                                                                                                                                                                                                                                                                                                            let carbKcal = target - proteinKcal - fatKcal;

                                                                                                                                                                                                                                                                                                                                                                                                                if (carbKcal < target * 0.15) {
                                                                                                                                                                                                                                                                                                                                                                                                                          proteinG = weightKg * 1.6;
                                                                                                                                                                                                                                                                                                                                                                                                                                proteinKcal = proteinG * 4;
                                                                                                                                                                                                                                                                                                                                                                                                                                      carbKcal = target - proteinKcal - fatKcal;
                                                                                                                                                                                                                                                                                                                                                                                                                                            if (carbKcal < target * 0.1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        fatKcal = target * 0.2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                fatG = fatKcal / 9;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        carbKcal = target * 0.35;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                proteinKcal = target - carbKcal - fatKcal;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        proteinG = proteinKcal / 4;
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                            const carbG = carbKcal / 4;

                                                                                                                                                                                                                                                                                                                                                                                                                                                const proteinPct = (proteinKcal / target) * 100;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const carbPct = (carbKcal / target) * 100;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const fatPct = (fatKcal / target) * 100;

                                                                                                                                                                                                                                                                                                                                                                                                                                                            // reveal results
                                                                                                                                                                                                                                                                                                                                                                                                                                                                resultsEmpty.style.display = 'none';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    resultsContent.classList.remove('show'); // restart entry animation on recalc
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        void resultsContent.offsetWidth;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            resultsContent.classList.add('show');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                lowCalWarning.style.display = capped ? 'block' : 'none';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const gaugePct = Math.max(6, Math.min(100, ((bmi - 15) / (40 - 15)) * 100));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        requestAnimationFrame(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  gaugeLiquid.style.height = gaugePct + '%';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (bmiMarker) bmiMarker.style.left = Math.max(0, Math.min(100, gaugePct)) + '%';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gaugeBmi.textContent = bmi.toFixed(1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bmiCategoryEl.textContent = cat.label;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bmiCategoryEl.style.color = cat.color;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        statBmr.textContent = Math.round(bmr).toLocaleString() + ' kcal';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            statTdee.textContent = Math.round(tdee).toLocaleString() + ' kcal';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                animateCount(statTarget, Math.round(target), ' kcal', 700);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    statPace.textContent = GOAL_LABELS[goal];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        requestAnimationFrame(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  barProtein.style.width = proteinPct + '%';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        barCarb.style.width = carbPct + '%';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              barFat.style.width = fatPct + '%';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            legProtein.textContent = Math.round(proteinG) + 'g';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                legCarb.textContent = Math.round(carbG) + 'g';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    legFat.textContent = Math.round(fatG) + 'g';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const program = matchProgram(cat.key, goal);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            planName.textContent = program.name;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                planTag.textContent = program.tag;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    planDesc.textContent = program.desc;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        planMeals.innerHTML = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            program.meals.forEach(([label, text]) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const row = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            row.className = 'plan-meal';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const b = document.createElement('b');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        b.textContent = label;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const span = document.createElement('span');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    span.textContent = text;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          row.append(b, span);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                planMeals.appendChild(row);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                resultsContent.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })();



                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                
                                                                                                                                                                                                                        
                                                                                                                                                                                            
                                                                                                                                                                                                
                                                                                                                                                              
                                                                                                                                                    
                                                                                                                                                        
                                                                                                                      
                                                                                                            
                                                                                                                
                                                                              
                                                                    
                                                              
                                                            
                                                  
                                            
                                            
                           